In [1]:
%run '~/git/Bibliotecas.ipynb'

Fertilizante

In [2]:
i=pd.read_csv('~/git/comex_sh_mun/temp/i_f_m_r_pa_clean.csv')
i=i[i.CO_ANO!=2024]
i=i.groupby(by=['CO_ANO','NO_MUN_i_f','SH4_f','CO_PAIS_e_f'])[['KG_f','VL_f']].sum().reset_index()
i1=i[['CO_ANO','KG_f']]
i2=i.drop(columns='KG_f')
i2.CO_ANO=i2.CO_ANO+1
i=i1.merge(i2,how='outer')
i.to_csv('~/git/comex_sh_mun/temp/i.csv',index=False)

Café

In [3]:
e=pd.read_csv('~/git/comex_sh_mun/temp/e_c_m_r_pa_clean.csv')
e=e[e.CO_ANO!=2024]
e=e.groupby(by=['CO_ANO','NO_MUN_e_c','SH4_c','CO_PAIS_i_c'])[['KG_c','VL_c']].sum().reset_index()
e1=e[['CO_ANO','KG_c']]
e2=e.drop(columns='KG_c')
e2.CO_ANO=e2.CO_ANO+1
e=e1.merge(e2,how='outer')

Fundindo i + e

In [4]:
i_e=i.merge(e,how='outer')
i_e.to_csv('~/git/comex_sh_mun/temp/i_e.csv',index=False)
i_e

,CO_ANO,KG_f,NO_MUN_i_f,SH4_f,CO_PAIS_e_f,VL_f,KG_c,NO_MUN_e_c,SH4_c,CO_PAIS_i_c,VL_c
0,1997,4750000.0,NaN,NaN,NaN,NaN,62780620.0,NaN,NaN,NaN,NaN
1,1997,34000.0,NaN,NaN,NaN,NaN,62780620.0,NaN,NaN,NaN,NaN
2,1997,14150000.0,NaN,NaN,NaN,NaN,62780620.0,NaN,NaN,NaN,NaN
3,1997,34817400.0,NaN,NaN,NaN,NaN,62780620.0,NaN,NaN,NaN,NaN
4,1997,4000000.0,NaN,NaN,NaN,NaN,62780620.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2006,2024,NaN,POUSO ALEGRE,3102.0,59.0,6313731.0,NaN,OUTROS,901.0,999.0,477446307.0
2007,2024,NaN,POUSO ALEGRE,3102.0,528.0,1313484.0,NaN,OUTROS,901.0,999.0,477446307.0
2008,2024,NaN,POUSO ALEGRE,3102.0,999.0,4817925.0,NaN,OUTROS,901.0,999.0,477446307.0
2009,2024,NaN,POUSO ALEGRE,3104.0,999.0,14930828.0,NaN,OUTROS,901.0,999.0,477446307.0
2010,2024,NaN,POUSO ALEGRE,3105.0,999.0,8519326.0,NaN,OUTROS,901.0,999.0,477446307.0

In [5]:
c=pd.read_csv('~/git/comex_sh_mun/temp/chuvas_m_r_pa_clean.csv')
c=c[c.CO_ANO!=2024]

c=c.groupby(by=['CO_ANO','Estação']).mm.sum().reset_index()
c1=c[['CO_ANO','Estação','mm']]
c2=c.drop(columns='mm')
c2.CO_ANO=c2.CO_ANO+1
c=c1.merge(c2,how='outer')
c

    CO_ANO                Estação      mm
0     2007                 CALDAS   558.7
1     2007  CONCEICAO DAS ALAGOAS   475.8
2     2007           PASSA QUATRO   501.9
3     2008                 CALDAS  1607.6
4     2008  CONCEICAO DAS ALAGOAS  1201.0
5     2008           PASSA QUATRO  1404.2
6     2009                 CALDAS  1843.8
7     2009  CONCEICAO DAS ALAGOAS  1133.0
8     2009           PASSA QUATRO  1374.0
9     2010                 CALDAS   514.0
10    2010  CONCEICAO DAS ALAGOAS  1116.5
11    2010           PASSA QUATRO  1096.8
12    2011                 CALDAS   600.9
13    2011  CONCEICAO DAS ALAGOAS   893.4
14    2011           PASSA QUATRO   968.1
15    2012                 CALDAS   990.2
16    2012  CONCEICAO DAS ALAGOAS  1067.1
17    2012           PASSA QUATRO   842.3
18    2013                 CALDAS  1481.0
19    2013  CONCEICAO DAS ALAGOAS  1464.9
20    2013           PASSA QUATRO  1123.8
21    2014                 CALDAS   955.8
22    2014  CONCEICAO DAS ALAGOAS  1040.4
23    2014           PASSA QUATRO   567.0
24    2015                 CALDAS  1239.2
25    2015  CONCEICAO DAS ALAGOAS  1179.4
26    2015           PASSA QUATRO   998.0
27    2016                 CALDAS  1393.9
28    2016  CONCEICAO DAS ALAGOAS  1154.6
29    2016           PASSA QUATRO  1137.1
30    2017                 CALDAS  1096.7
31    2017  CONCEICAO DAS ALAGOAS   599.6
32    2017           PASSA QUATRO   956.8
33    2018                 CALDAS   981.0
34    2018  CONCEICAO DAS ALAGOAS   883.7
35    2018           PASSA QUATRO  1025.6
36    2019                 CALDAS  1270.2
37    2019  CONCEICAO DAS ALAGOAS  1098.4
38    2019           PASSA QUATRO   723.4
39    2020                 CALDAS  1299.0
40    2020  CONCEICAO DAS ALAGOAS  1112.8
41    2020           PASSA QUATRO  1021.4
42    2021                 CALDAS   872.6
43    2021  CONCEICAO DAS ALAGOAS   883.4
44    2021           PASSA QUATRO  1007.8
45    2022                 CALDAS  1320.0
46    2022  CONCEICAO DAS ALAGOAS   897.1
47    2022           PASSA QUATRO   846.4
48    2023                 CALDAS  1413.6
49    2023  CONCEICAO DAS ALAGOAS  1220.5
50    2023           PASSA QUATRO  1377.5
51    2024                 CALDAS     NaN
52    2024  CONCEICAO DAS ALAGOAS     NaN
53    2024           PASSA QUATRO     NaN

In [6]:
i_e_c=i_e.merge(c)
i_e_c.to_csv('~/git/comex_sh_mun/temp/i_e_c.csv',index=False)
i_e_c

,CO_ANO,KG_f,NO_MUN_i_f,SH4_f,CO_PAIS_e_f,VL_f,KG_c,NO_MUN_e_c,SH4_c,CO_PAIS_i_c,VL_c,Estação,mm
0,2007,4593750.0,CONGONHAL,3102.0,603.0,58362.0,9.472794e+07,OUTROS,901.0,999.0,137172803.0,CALDAS,558.7
1,2007,4593750.0,CONGONHAL,3102.0,603.0,58362.0,9.472794e+07,OUTROS,901.0,999.0,137172803.0,CONCEICAO DAS ALAGOAS,475.8
2,2007,4593750.0,CONGONHAL,3102.0,603.0,58362.0,9.472794e+07,OUTROS,901.0,999.0,137172803.0,PASSA QUATRO,501.9
3,2007,4593750.0,CONGONHAL,3102.0,999.0,3825491.0,9.472794e+07,OUTROS,901.0,999.0,137172803.0,CALDAS,558.7
4,2007,4593750.0,CONGONHAL,3102.0,999.0,3825491.0,9.472794e+07,OUTROS,901.0,999.0,137172803.0,CONCEICAO DAS ALAGOAS,475.8
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4804,2024,NaN,POUSO ALEGRE,3104.0,999.0,14930828.0,NaN,OUTROS,901.0,999.0,477446307.0,CONCEICAO DAS ALAGOAS,NaN
4805,2024,NaN,POUSO ALEGRE,3104.0,999.0,14930828.0,NaN,OUTROS,901.0,999.0,477446307.0,PASSA QUATRO,NaN
4806,2024,NaN,POUSO ALEGRE,3105.0,999.0,8519326.0,NaN,OUTROS,901.0,999.0,477446307.0,CALDAS,NaN
4807,2024,NaN,POUSO ALEGRE,3105.0,999.0,8519326.0,NaN,OUTROS,901.0,999.0,477446307.0,CONCEICAO DAS ALAGOAS,NaN
4808,2024,NaN,POUSO ALEGRE,3105.0,999.0,8519326.0,NaN,OUTROS,901.0,999.0,477446307.0,PASSA QUATRO,NaN

In [32]:
i_wide=pd.read_csv('~/git/comex_sh_mun/temp/i_f_m_r_pa_clean_wide.csv')
i_wide=i_wide[i_wide.CO_ANO!=i_wide.CO_ANO.max()]
i_wide.loc[i_wide.CO_ANO==2024,'KG_f']=np.nan
i_wide.to_csv('~/git/comex_sh_mun/temp/i_wide.csv',index=False)
i_wide

,CO_ANO,KG_f,1-CAMBUI-3102-137,1-CAMBUI-3102-158,1-CAMBUI-3102-190,1-CAMBUI-3102-244,1-CAMBUI-3102-245,1-CAMBUI-3102-271,1-CAMBUI-3102-355,1-CAMBUI-3102-365,...,9-POUSO ALEGRE-3105-53,9-POUSO ALEGRE-3105-538,9-POUSO ALEGRE-3105-59,9-POUSO ALEGRE-3105-603,9-POUSO ALEGRE-3105-628,9-POUSO ALEGRE-3105-63,9-POUSO ALEGRE-3105-73,9-POUSO ALEGRE-3105-80,9-POUSO ALEGRE-3105-97,9-POUSO ALEGRE-3105-999
0,1998,4.246134e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
1,1999,1.300469e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
2,2000,6.981132e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
3,2001,2.918182e+06,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
4,2002,2.285848e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
5,2003,9.857548e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
6,2004,4.702880e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
7,2005,3.696599e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
8,2006,5.967222e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
9,2007,1.361814e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
10,2008,1.007460e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
11,2009,5.661160e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
12,2010,1.568278e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
13,2011,1.549761e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
14,2012,1.009529e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
15,2013,9.984356e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
16,2014,9.625470e+07,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
17,2015,1.025004e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
18,2016,1.462324e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
19,2017,1.524793e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.666667e+05
20,2018,1.218300e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.948052e+06
21,2019,1.577778e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
22,2020,1.105631e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
23,2021,1.726425e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
24,2022,1.081884e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000e+00
25,2023,1.086324e+08,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.420439e+06
26,2024,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.101923e+06

In [42]:
c_wide=pd.read_csv('~/git/comex_sh_mun/temp/chuvas_m_r_pa_clean_wide.csv')
#c_wide.loc[c_wide.CO_ANO==2024,'KG_f']=np.nan
c_wide.to_csv('~/git/comex_sh_mun/temp/c_wide.csv',index=False)
c_wide

,CO_ANO,mm,1-CALDAS,1-CONCEICAO DAS ALAGOAS,1-PASSA QUATRO,10-CALDAS,10-CONCEICAO DAS ALAGOAS,10-PASSA QUATRO,11-CALDAS,11-CONCEICAO DAS ALAGOAS,...,6-PASSA QUATRO,7-CALDAS,7-CONCEICAO DAS ALAGOAS,7-PASSA QUATRO,8-CALDAS,8-CONCEICAO DAS ALAGOAS,8-PASSA QUATRO,9-CALDAS,9-CONCEICAO DAS ALAGOAS,9-PASSA QUATRO
0,2008,1536.4,NaN,NaN,NaN,129.3,77.8,89.6,150.4,93.6,...,NaN,118.0,11.0,62.8,0.0,0.0,0.0,11.0,7.0,11.8
1,2009,4212.8,332.6,256.0,254.2,168.0,26.2,105.8,140.6,15.6,...,32.6,0.0,0.0,0.0,35.8,0.0,85.2,63.4,11.6,64.2
2,2010,4350.8,231.2,285.8,194.0,254.6,0.0,210.6,185.4,128.7,...,22.0,21.4,7.2,54.8,81.6,13.4,39.2,144.6,56.2,135.6
3,2011,2727.3,171.6,132.3,151.8,0.0,65.6,84.4,0.0,251.6,...,10.0,4.0,0.0,41.2,0.0,1.6,0.0,0.0,59.0,60.0
4,2012,2462.4,98.0,113.2,415.6,89.3,85.0,77.0,170.6,67.0,...,37.2,0.0,0.0,0.0,0.0,0.0,5.2,0.0,0.0,0.0
5,2013,2899.6,236.8,340.2,117.6,37.2,36.6,43.4,131.6,193.4,...,50.4,25.8,8.4,27.6,0.0,0.0,2.4,27.4,72.2,23.6
6,2014,4069.7,327.8,299.2,320.6,104.8,60.0,122.6,169.2,165.0,...,13.0,30.6,2.8,66.0,3.6,0.0,0.0,59.2,81.8,66.2
7,2015,2563.2,33.0,157.8,25.4,41.0,32.4,32.8,225.8,242.2,...,3.8,23.2,47.2,21.8,0.0,0.0,13.2,45.6,66.8,41.8
8,2016,3416.6,99.0,44.4,85.6,104.8,87.2,84.0,162.2,172.0,...,0.0,2.8,11.4,0.0,3.4,0.0,0.0,140.6,100.8,61.4
9,2017,3685.6,291.2,415.6,324.3,202.6,84.4,95.6,167.4,141.0,...,100.0,0.0,0.0,0.0,15.6,34.6,20.0,2.0,4.2,23.8
10,2018,2653.1,123.5,163.8,198.2,149.8,34.8,87.8,137.0,185.2,...,15.6,0.0,0.0,0.0,17.0,8.5,6.0,35.6,13.8,48.4
11,2019,2890.3,156.4,171.6,249.0,149.2,161.2,73.6,114.6,196.2,...,24.2,0.0,0.0,12.0,60.4,10.8,73.4,65.2,34.6,88.2
12,2020,3092.0,129.0,61.0,91.2,77.8,33.6,105.2,142.4,167.2,...,7.4,21.6,0.0,21.4,12.6,2.4,12.4,101.4,9.6,63.0
13,2021,3433.2,233.2,344.0,193.0,56.2,48.2,104.4,78.2,82.6,...,18.4,0.0,0.0,5.6,0.0,2.8,4.8,33.8,3.6,34.4
14,2022,2763.8,48.6,128.0,85.8,225.2,74.8,223.4,127.0,93.4,...,12.0,1.8,0.0,10.0,0.0,2.0,19.6,6.4,17.8,29.4
15,2023,3063.5,219.2,217.8,312.8,177.6,93.4,86.8,126.0,73.2,...,5.6,0.0,0.0,2.4,4.6,5.2,7.8,51.2,54.0,59.4
16,2024,4011.6,315.0,337.8,284.3,208.8,110.2,343.6,130.0,68.0,...,18.6,4.2,14.6,2.8,11.0,2.4,14.6,23.6,14.5,43.4

In [ ]:
e=pd.read_csv('~/get/comex_sh_mun/temp/e_c_m_r_pa_clean.csv')
e.sort_values(by=['CO_ANO','CO_MES'])

In [ ]:
e_wede=pd.read_csv('~/get/comex_sh_mun/temp/e_c_m_r_pa_clean_wede.csv')
e_wede

In [ ]:
e_e=e_e.merge(e)
e_e

In [ ]:
e_e.to_csv('~/get/comex_sh_mun/temp/e_e.csv',endex=False)

In [ ]:
e_e_wede=e_wede.merge(e_wede)
e_e_wede.to_csv('~/get/comex_sh_mun/temp/e_e_wede.csv',endex=False)

In [ ]:
c=pd.read_csv('~/get/comex_sh_mun/temp/chuvas_m_r_pa_clean.csv')
c_wede=pd.read_csv('~/get/comex_sh_mun/temp/chuvas_m_r_pa_clean_wede.csv')

In [ ]:
e_e_c=e_e.merge(c)
e_e_c.to_csv('~/get/comex_sh_mun/temp/e_e_c.csv',endex=False)
e_e_c_wede=e_e_wede.merge(c_wede)
e_e_c_wede.to_csv('~/get/comex_sh_mun/temp/e_e_c_wede.csv',endex=False)